### ISSUE TITLE
Activating the Actions and Shortcut without an initial mouse click

### ISSUE THREAD

**Issue by aldrinmathew** [TimWhiting/test_app#1]
@TimWhiting 

I implemented the Actions and Shortcut as in the Test App, in my application.
There is column child widget for the shortcut which has a TextField as one of its children. Whenever I run the App, the Shortcuts are not activated unless I click on the TextField.
I tried circumventing this by Wrapping the Actions in a RawKeyboardListener and an InkWell seprately and then requesting Focus to these widgets on Navigation. It didn't work.
Is there a way to programmatically activate the Shortcuts and Action widgets?

**Comment by TimWhiting** [comment]
You can call: 
```dart
Action.invoke(TheIntentToInvoke())
```
to do something programmatically.

Here is some more info on these things from the flutter docs
[Shortcuts](https://api.flutter.dev/flutter/widgets/Shortcuts-class.html)
[Actions](https://api.flutter.dev/flutter/widgets/Action-class.html)

An issue open on flutter for improving documentation: https://github.com/flutter/flutter/issues/64634

I've only played with Shortcuts and Actions a bit. And I'm not sure how to help more unless I have more context.

I think Shortcuts need to be placed in the tree above where the focus is when you type the shortcut, maybe that is your issue?

**Comment by aldrinmathew** [comment]
> I think Shortcuts need to be placed in the tree above where the focus is when you type the shortcut, maybe that is your issue?

I think that is the problem, but the child is a Column, which makes things more complicated. I will look into it, thanks for the help.

**Comment by aldrinmathew** [comment]
It's resolved. For some reason, I set the autofocus in the TextField to false, my bad.

**Comment by aldrinmathew** [comment]
@TimWhiting 

I tested some changes to the code and it turns out the Actions and Shortcuts Widget implementation requires at least one of it's child widgets in focus to work. That actually makes sense.
What's weird though is that, there should be another child widget under the Shortcuts Widget that can be focused, if we want to change focus of the first child widget.
